### ISSUE TITLE
The ingest_slug default with its associated template usage do not follow Python naming convention

### ISSUE THREAD

**Issue by kefeimo** [tsdat/pipeline-template#4]
## Describe the bug
(A clear and concise description of what the bug is.)
The ingest_slug default with its associated template usage do not follow Python naming convention. i.e., location should not be included in the ingest_slug default.

## Steps to Reproduce
```
# when run the following and then answer the prompt questions
cookiecutter templates/ingest -o ingest/
```

If applicable, include the full traceback below:
(Not applicable)

## Screenshots
<img width="493" alt="image" src="https://user-images.githubusercontent.com/28743873/163488065-db5fbb73-87dc-4305-bab6-8ffda0c64b96.png">

## System Information:
(Not applicable)

## Additional context
(Add any other context about the problem here.)

Quote the definition of slug in Documentation: https://tsdat.readthedocs.io/
> Note: the term “slug” here means directory names.

Preview of usage for {{ cookiecutter.ingest_slug }}
<img width="697" alt="image" src="https://user-images.githubusercontent.com/28743873/163489079-56728c97-00f5-4699-9d0d-e0dede1e966a.png">

**Comment by maxwellevin** [comment]
@kefeimo I've thought about this one a lot and I kept changing my mind about whether or not the location should be included in the ingest slug. I eventually 'settled' on including it, but really I'm not so sure that was the right call. I'm curious what your thoughts are here; what is your reasoning for removing it?

**Comment by kefeimo** [comment]
@maxwellevin Thanks for responding to this issue. The comment above is related to my inexperienced with tsdat-template. So, my apology if the concern is not aligned with a seasoned tsdat developer. Back to the issue itself.

Some back story:
* I misinterpreted the term "Location". (The fact that question is right after "author" and "email" makes me think it is asking my personal information, like where I live. And I though it makes no sense to include personal info as part of the project name.)
* Call me lazy, but I didn't read through the readme, which has all the definitions about the terms. For example: location: The name of the location where the instrument or ingest is located. And that makes a lot of sense for data ingest project naming.
* In addition, in James example, there is no location involved (from that example the ingest_slug default was overridden.) https://tsdat.readthedocs.io/en/latest/_images/vscode12.png
* However, at this point, I would argue the root cause is Cookiecutter's question prompt. I also realized Cookiecutter lacks the feature, at least, not very straightforward to include instructions in the question list. Thus it can easily cause confusion for user just want to try the template out without going through all the documentation. (On a side note, Coppier does have a richer options to design the question prompt.)

To mitigate this, I have played with some walkaround to add instruction to the question prompt. Though the solution is not pretty, I hope it can improve user experience by including instructions.
(note: inspired by [Include help/instructions in cookiecutter prompts](https://www.guidodiepen.nl/2021/05/include-help-instructions-in-cookiecutter-prompts/)
<img width="430" alt="image" src="https://user-images.githubusercontent.com/28743873/163666705-5a3d9d8b-c4ac-4e63-8d84-164f99bfc6b2.png">

**Comment by maxwellevin** [comment]
@kefeimo ah, I see; the placement & lack of direct info about the 'location' prompt made it seem like it was author location. Your suggestion of adding helper text seems logical, but I think we can also help provide context implicitly just by changing the order of the prompts & name of the variables.

What if we changed it so that `location` comes after `ingest` and before `ingest_slug`? If we're doing that, then I might also want to rename some of these variables so their names also communicate the information better, see below:

```json
{
  "author_name": "First Last",
  "author_email": "",
  "ingest_title": "Title of the Ingest",
  "ingest_location": "Location of the Instrument/Data",
  "ingest_location_slug": "{{ cookiecutter.location | slugify(separator='_') }}",
  "ingest_slug": "{{ cookiecutter.ingest | slugify(separator='_') }}_{{ cookiecutter.location_slug }}",
  "ingest_description": "Overview of the ingest and motivation. This can be updated later in the README.md and the pipeline configuration file.",
  "use_custom_filehandler": [
    "no",
    "yes"
  ],
  "use_custom_qc": [
    "no",
    "yes"
  ],
  "add_help": [
    "yes",
    "no"
  ]
}
```

**Comment by kefeimo** [comment]
> @kefeimo ah, I see; the placement & lack of direct info about the 'location' prompt made it seem like it was author location. Your suggestion of adding helper text seems logical, but I think we can also help provide context implicitly just by changing the order of the prompts & name of the variables.
> 
> What if we changed it so that `location` comes after `ingest` and before `ingest_slug`? If we're doing that, then I might also want to rename some of these variables so their names also communicate the information better, see below:
> 
> ```json
> {
>   "author_name": "First Last",
>   "author_email": "",
>   "ingest_title": "Title of the Ingest",
>   "ingest_location": "Location of the Instrument/Data",
>   "ingest_location_slug": "{{ cookiecutter.location | slugify(separator='_') }}",
>   "ingest_slug": "{{ cookiecutter.ingest | slugify(separator='_') }}_{{ cookiecutter.location_slug }}",
>   "ingest_description": "Overview of the ingest and motivation. This can be updated later in the README.md and the pipeline configuration file.",
>   "use_custom_filehandler": [
>     "no",
>     "yes"
>   ],
>   "use_custom_qc": [
>     "no",
>     "yes"
>   ],
>   "add_help": [
>     "yes",
>     "no"
>   ]
> }
> ```

It looks much more expressive and easier to understand to me. 

Another question: do we want "use_custom_filehandler: no" as default? Since it is more expensive for the user to get `filehandler.py` back or even realize it is an option than deleting it later.

**Comment by maxwellevin** [comment]
> Another question: do we want "use_custom_filehandler: no" as default? Since it is more expensive for the user to get `filehandler.py` back or even realize it is an option than deleting it later.

I was just trying to keep the order consistent for the filehandler and qc and people hardly use custom qc, at least from what I've seen. However, I agree it is easier to remove stuff than it is to add it in, at least as a new user, so I'm okay with switching these both to default to "yes".

**Comment by maxwellevin** [comment]
@kefeimo I'm closing this issue since the author information is removed from the Cookiecutter prompt (git commit history is probably better anyways).
