### ISSUE TITLE
Unclear how to run the pipeline

### ISSUE THREAD

**Issue by maxwellevin** [tsdat/pipeline-template#8]
## Describe the bug
It is unclear how to run the pipeline because there are no explicit instructions on how to do this. 

## Expected behavior
Instructions for first-time users on how to run their pipelines.

## Additional context
N/A

**Comment by kefeimo** [comment]
Potential solution
- suggestion: complete the example, especially the test case example (e.g., [c8b32ee](https://github.com/tsdat/pipeline-template/commit/c8b32ee5eec381793c32d4de681d891ee6240f87)) and the runner.py (to explain how to use the inherent ExamplePipeline class). (advantage: self-explained, reproduceable, maintenance enforcement 
- bottom line: describe in documentation (drawbacks: users might ignore documentation, extra maintenance effort, not as self-explained, reproducibility unclear)

**Comment by maxwellevin** [comment]
@clansing has been working on some documentation updates for the template. Carina, can you reference / close this issue when you push your changes?

**Comment by maxwellevin** [comment]
Carina's changes have been merged. Closing this
